spring:  
  config:
    activate:
      on-profile:
      - dev
  cloud:
    consul:
      discovery:
        instance-id: "${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}"
        instance-zone: dev
        # health-check-path: "/customer-service-check"
        # health-check-interval: 20s
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    '[org.springframework.web.filter.CommonsRequestLoggingFilter]': DEBUG

server:
  port: 0